### PR TITLE
feat: StdResult (de)serializer

### LINKED ISSUE #314: [WASM] implement (de)serializer to StdError
This is because the returned value of callable points needs available to (de)serialize.
Now `StdError` cannot be serialize, so callable point cannot return StdResult.

### PR DESCRIPTION
**Pull request by dudong2**
# Description

Closes #314 

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [x] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/Finschia/cosmwasm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

### CODE REVIEW

**Review by da1suk8 — COMMENTED** [review]
I have 2 questions. Please confirm.


- please explain why conversion_overflow() was added.
- I tried to compile and got this warning. Is this intended?

```
$pwd
./cosmwasm/contracts/dynamic-caller-contract
$cargo wasm
warning: unused import: `StdError`
 --> src/contract.rs:3:42
  |
3 |     DepsMut, Env, MessageInfo, Response, StdError, StdResult, Uint128,
  |                                          ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `dynamic-caller-contract` (lib) generated 1 warning
```

**Comment by dudong2** [comment]
> I have 2 questions. Please confirm.
> 
> * please explain why conversion_overflow() was added.
> * I tried to compile and got this warning. Is this intended?
> 
> ```
> $pwd
> ./cosmwasm/contracts/dynamic-caller-contract
> $cargo wasm
> warning: unused import: `StdError`
>  --> src/contract.rs:3:42
>   |
> 3 |     DepsMut, Env, MessageInfo, Response, StdError, StdResult, Uint128,
>   |                                          ^^^^^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default
> 
> warning: `dynamic-caller-contract` (lib) generated 1 warning
> ```
* conversion_overflow() is a function that hasn't been accidentally cleared yet. I removed it thanks to a comment.
* StdError is being used [here](https://github.com/Finschia/cosmwasm/pull/313/files#diff-034266d0dbc7e843b378e05bd3c7c3c98c9435e81a518bbe020615543c782e7dR94-R96). I got the same warning with the `cargo wasm` command, but I'm not sure why. any ideas?

**Comment by loloicci** [comment]
> StdError is being used [here](https://github.com/Finschia/cosmwasm/pull/313/files#diff-034266d0dbc7e843b378e05bd3c7c3c98c9435e81a518bbe020615543c782e7dR94-R96). I got the same warning with the cargo wasm command too, but I'm not sure why. any ideas?

StdError is only used in `#[cfg(not(target_arch = "wasm32"))]` area and `cosmwasm_std::StdError` is imported and not used if the target is wasm. So, rewrite import like

```
#[cfg(not(target_arch = "wasm32"))]
use cosmwasm_std::StdError
```

**Comment by dudong2** [comment]
> 

However, for other contracts like hackatom, `#[cfg(not(target_arch = "wasm32"))]` was not added. However, in hackatom, the cargo wasm did not output any other warnings.

**Comment by dudong2** [comment]
> > StdError is being used [here](https://github.com/Finschia/cosmwasm/pull/313/files#diff-034266d0dbc7e843b378e05bd3c7c3c98c9435e81a518bbe020615543c782e7dR94-R96). I got the same warning with the cargo wasm command too, but I'm not sure why. any ideas?
> 
> StdError is only used in `#[cfg(not(target_arch = "wasm32"))]` area and `cosmwasm_std::StdError` is imported and not used if the target is wasm. So, rewrite import like
> 
> ```
> #[cfg(not(target_arch = "wasm32"))]
> use cosmwasm_std::StdError
> ```

However, for other contracts like hackatom, #[cfg(not(target_arch = "wasm32"))] was not added. However, in hackatom, the cargo wasm did not output any other warnings.

**Comment by loloicci** [comment]
> However, for other contracts like hackatom, #[cfg(not(target_arch = "wasm32"))] was not added. However, in hackatom, the cargo wasm did not output any other warnings.

This is because hackatom uses StdError for also wasm target.
https://github.com/Finschia/cosmwasm/blob/5f77927a932e19452ffea6d88f121fbbc211eeca/contracts/hackatom/src/contract.rs#L43

Try `cosmwasm_std::StdResult` in `#[cfg(not(target_arch = "wasm32"))]` area or use `cosmwasm_std::StdResult` instead `StdResult` without importing it.

**Review by loloicci — APPROVED** [review]

**Review by da1suk8 — APPROVED** [review]

**Pull request merged**
