### PR TITLE
feat: enable sign ext for wasm generated with rust 1.70

### PR DESCRIPTION
**Pull request by loloicci**
# Description
This PR enable sign-ext feature of parity wasm.
This allows wasm to use some additional operators which are sometimes used in wasm generated with rust1.70.

This fix https://github.com/Finschia/cosmwasm/issues/338. 
And, this will be replaced with wasmparser in a feature version (https://github.com/CosmWasm/cosmwasm/pull/1786).

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [x] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/Finschia/cosmwasm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly. (not needed)
- [x] I have added tests to cover my changes.
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

### CODE REVIEW

**Review by zemyblue — APPROVED** [review]

**Comment by tkxkd0159** [comment]
Why don't we replace parity-wasm with [wasmer::wasmparser](https://crates.io/crates/wasmparser)?
Upstream already applied it and I assume there is no dependency before apply this.

ref. https://github.com/CosmWasm/cosmwasm/pull/1786

**Review by tkxkd0159 — COMMENTED** [review]
Why don't we replace parity-wasm with [wasmer::wasmparser](https://crates.io/crates/wasmparser)?
Upstream already applied it and I assume there is no dependency to apply this.

ref. https://github.com/CosmWasm/cosmwasm/pull/1786

**Comment by 170210** [comment]
@tkxkd0159 It already been merged into bump_1.5.1 branch, do you mean we need merge it to main branch first? https://github.com/Finschia/cosmwasm/blob/feat/bump_1.5.1/packages/vm/src/cache.rs#L17

**Comment by loloicci** [comment]
@tkxkd0159 

> Why don't we replace parity-wasm with [wasmer::wasmparser](https://crates.io/crates/wasmparser)?

This is because some interfaces of wasmparser in wasmer 4.1.0 used by https://github.com/CosmWasm/cosmwasm/pull/1786 is not compatible with wasmer 2.3.0 which we use in main.
So, as I said in the description, this will be replaced in future version.

> this will be replaced with wasmparser in a feature version (https://github.com/CosmWasm/cosmwasm/pull/1786).

**Review by zemyblue — APPROVED** [review]

**Comment by tkxkd0159** [comment]
> @tkxkd0159
> 
> > Why don't we replace parity-wasm with [wasmer::wasmparser](https://crates.io/crates/wasmparser)?
> 
> This is because some interfaces of wasmparser in wasmer 4.1.0 used by [CosmWasm/cosmwasm#1786](https://github.com/CosmWasm/cosmwasm/pull/1786) is not compatible with wasmer 2.3.0 which we use in main. So, as I said in the description, this will be replaced in future version.
> 
> > this will be replaced with wasmparser in a feature version ([CosmWasm/cosmwasm#1786](https://github.com/CosmWasm/cosmwasm/pull/1786)).

Okay, I understand now. LGTM

**Review by tkxkd0159 — APPROVED** [review]

**Pull request merged**
